import './Alces alces.svg';
import './Ammotragus lervia.svg';
import './Atelerix algirus.svg';
import './Atlantoxerus getulus.svg';
import './Axis axis.svg';
import './Bison bonasus.svg';
import './Canis aureus.svg';
import './Canis lupus.svg';
import './Capra ibex.svg';
import './Capra pyrenaica.svg';
import './Capreolus capreolus.svg';
import './Castor fiber.svg';
import './Cervus elaphus.svg';
import './Cervus nippon.svg';
import './Dama dama.svg';
import './Erinaceus concolor.svg';
import './Erinaceus europaeus.svg';
import './Felis silvestris.svg';
import './Genetta genetta.svg';
import './Herpestes auropunctatus.svg';
import './Herpestes ichneumon.svg';
import './Lepus castroviejoi.svg';
import './Lepus europaeus.svg';
import './Lepus granatensis.svg';
import './Lepus timidus.svg';
import './Lutra lutra.svg';
import './Lynx lynx.svg';
import './Lynx pardinus.svg';
import './Marmota marmota.svg';
import './Meles meles.svg';
import './Myocastor coypus.svg';
import './Nyctereutes procyonoides.svg';
import './Odocoileus virginianus.svg';
import './Oryctolagus cuniculus.svg';
import './Ovis ammon.svg';
import './Procyon lotor.svg';
import './Rupicapra pyrenaica.svg';
import './Rupicapra rupicapra.svg';
import './Sciurus vulgaris.svg';
import './Spermophilus suslicus.svg';
import './Spermophilus citellus.svg';
import './Sus scrofa.svg';
import './Ursus arctos.svg';
import './Vulpes vulpes.svg';
import './Macropus rufogriseus.svg'
import './Hemiechinus auritus.svg'
import './Sylvilagus floridanus.svg'
import './Lepus capensis.svg'
import './Lepus corsicanus.svg'
import './Sciurus anomalus.svg'
import './Sciurus carolinensis.svg'
import './Sciurus meridionalis.svg'
import './Callosciurus erythraeus.svg'
import './Callosciurus finlaysonii.svg'
import './Spermophilus pygmaeus.svg'
import './Marmota bobak.svg'
import './Pteromys volans.svg'
import './Tamias sibiricus.svg'
import './Castor canadensis.svg'
import './Hystrix cristata.svg'
import './Ursus maritimus.svg'
import './Alopex lagopus.svg'
import './Mustela erminea.svg'
import './Mustela eversmanii.svg'
import './Mustela lutreola.svg'
import './Mustela nivalis.svg'
import './Mustela putorius.svg'
import './Neovison vison.svg'
import './Martes foina.svg'
import './Martes martes.svg'
import './Vormela peregusna.svg'
import './Gulo gulo.svg'
import './Capra aegagrus.svg'
import './Ovibos moschatus.svg'
import './Rangifer tarandus.svg'
import './Muntiacus reevesi.svg'
import './Hydropotes inermis.svg'

